services:
  - type: web
    name: clinicavidah
    env: node
    buildCommand: yarn build && yarn start
    startCommand: node dist/index.js
    envVars:
      - key: VITE_API_URL
        sync: false
